[package]
name = "directory"
version = "0.1.0"
edition = "2024"

[dependencies]
color-eyre = "0.6.5"
derive_more = { version = "2.1.1", features = ["full"] }
jwalk = "0.9.0"
paste = "1.0.15"
rand = { version = "0.10.2", features = ["thread_rng"] }
rayon = "1.12.0"
serde = { version = "1.0.229", features = ["derive"] }
strum = { version = "0.28.0", features = ["derive"] }
toml = { version = "1.1.5", features = ["serde"] }
